### ISSUE TITLE
No color on composite video output

### ISSUE THREAD

**Issue by ezod** [jblang/rc9918#13]
I built this module from parts sourced myself without difficulty, but the composite video signal is not displaying color, only grayscale.

A similar issue was discussed [here](https://www.msx.org/forum/msx-talk/hardware/tms9918-not-displaying-color) and [here](https://github.com/InPermutation/tms9918a-arduino/issues/1), and the eventual resolution had to do with the accuracy of the crystal frequency. Indeed, the exact crystal specified in the BOM is no longer available, and I used [this part from Mouser](https://www.mouser.ca/ProductDetail/ECS/ECS-107.3-S-4X?qs=CNVyLAqdhH3eznbdvp7RRg%3D%3D) instead, but based on the datasheets and other implementations this part looks like it should work. Michael Kamprath, who sells the Tindie kits, independently suggested this same part as a replacement. Its datasheet specifies a 20pF load capacitance; I tried the 16pF and 22pF caps I had on hand with the same result in both cases.

Another suggestion was that the TMS9918A (sourced from an eBay seller in China) might in fact be a relabeled TMS9928A or TMS9929A, as these output Y (luminance) on pin 36 instead of COMVID. Perhaps there is a way with just the chip I have to definitively determine whether this is the case? Unfortunately, for the moment, I do not have another TMS9918A on hand to try.

Is there anything else I should check that might be the problem here, before I try my luck with another month-plus wait for a TMS9918A?

**Comment by apoloval** [comment]
> Another suggestion was that the TMS9918A (sourced from an eBay seller in China) might in fact be a relabeled TMS9928A or TMS9929A, as these output Y (luminance) on pin 36 instead of COMVID.

I bet for this one. 

Do you have an oscilloscope? It is really easy to confirm if you had one.

**Comment by ezod** [comment]
I do have an oscilloscope. What am I looking for? I'm not very familiar with analog video signals.

**Comment by apoloval** [comment]
You can make a particular test on pin 35. In TMS9918, this is the `EXTVDP` input signal. While in TMS9928/29 it is `B-Y`, an output signal that contains color information. 

If you observe a plain zero signal in the oscilloscope, or a pure noise wave, your part is a TMS9918. If you observe a video-like waveform as the following one, it is a TMS9928/29:

![image](https://user-images.githubusercontent.com/738507/196214605-328b525e-124b-43c4-822c-2aa36d77fd7a.png)

**Comment by ezod** [comment]
Pin 35 appears to just be a bit of white noise hovering near 5V. It definitely looks different than the signal on pin 36.

**Comment by ezod** [comment]
Given that it seems I have a genuine TMS9918, I found [this thread](https://www.retrobrewcomputers.org/n8vem-gg-archive/html-2010/Jan/msg00049.html) discussing a similar issue, suggesting that the crystal frequency isn't the only potential issue. I've ordered a [MP107-E](https://www.digikey.ca/en/products/detail/cts-frequency-controls/MP107-E/2637557) parallel resonant crystal along with some 33pF capacitors (hopefully close enough to the specified 32pF), similar to the part that worked for the OP, and will update here if that works.

**Comment by ezod** [comment]
And it works! Closing, but hopefully this will help anyone who encounters this issue in the future.
