### ISSUE TITLE
Ask for clarification: why do we need a voltage buffer for COMVID

### ISSUE THREAD

**Issue by apoloval** [jblang/rc9918#4]
According to the schematic, there is a NPN, emitter-follower transistor circuit that seems to be there as a voltage buffer for COMVID signal. 

<img width="254" alt="Captura de pantalla 2019-03-12 a las 20 35 14" src="https://user-images.githubusercontent.com/738507/54230383-98f7ae80-4506-11e9-9c76-6125d09da65a.png">

Thanks to this buffer, we may have a low output impedance. However, according to the TMS9918 datasheet, the VDP already have a MOS source-follower that would do exactly the same the NPN is doing.

<img width="636" alt="Captura de pantalla 2019-03-12 a las 20 40 04" src="https://user-images.githubusercontent.com/738507/54230664-318e2e80-4507-11e9-83aa-dd2154ddf9bb.png">

My question is, why do we need such NPN circuit for COMVID?

Thanks in advance for your help.

**Comment by jblang** [comment]
As I stated in the README, I started with a circuit designed by [Tom LeMense](https://retrobrewcomputers.org/n8vem-pbwiki-archive/0/35845334/48860720/33053543/SRAM%20Replacement%20for%20TMS99x8%20VRAM.pdf) and simply added address decoding and laid it out on a PCB. I did not put much thought into why he designed the output stage the way he did; I just copied it verbatim. You are right that it may not be necessary.

**Comment by apoloval** [comment]
Okay. Thank you so much for your response. It is really interesting, since most of the circuits I've seen using TMS9918 use a transistor at COMVID output. I will try to contact Tom to see if he could clarify this. 

Again, thank you so much for your time! And congrats for this awesome project!

**Comment by justinmoor** [comment]
Same question here. I've got a 100% working TMS9918 with SRAM interfaced to a 6502 without the voltage buffer circuit or ferrite bead. COMVID is directly connected (with 470 ohm resistor) to the video input of the monitor (Sony PVM). Everything seems to be working fine. Any update on this?

**Comment by apoloval** [comment]
I emailed Tom in 2019 asking the same question here. But I am afraid I received no response. 

I still don't know why this output stage. But I also confirm I have working designs that do not have it.

**Comment by cbmeeks** [comment]
For the record, I've also connected just a 330 ohm resistor from COMVID to GND and it worked just fine on a vanilla TV.  In fact, it was very colorful and vibrant.

**Comment by apoloval** [comment]
In my case I am using 470 Ohms, also with nice results:

![image](https://user-images.githubusercontent.com/738507/165693274-f2802698-ae01-43f9-866e-df1cc31d6fd0.png)

The design is open source, available in https://github.com/artemisamsx/gfx9918.

**Comment by michaelkamprath** [comment]
Section 3.4.1 and 4.2.2 of [the TMS9918A spec](http://www1.cs.columbia.edu/~sedwards/papers/TMS9918.pdf) clearly states that in most cases, a 330 Ω or 470 Ω pull down resistor on the COMVID line is what is needed. But they also states that "in some cases it may be necessary to provide a simple interface circuit to match the monitor's input requirements." The use of the transistor on the COMVID line is that circuit, and it there as a simple precaution as it electrically isolates the rare, expensive, and no longer produced TMS9918A chip from external electrical interfaces. If the monitor draws more current than the TMS9918A can supply, well, that doesn't happen with the transistor circuit in this card's current design. Is it strictly needed? No. Does adding a 25 cent (if that) part provide some electrical isolation for the TMSD9918A chip? Yes.

**Comment by apoloval** [comment]
I find the usage of the buffer for protection purposes convincing. Just wanted to know if there was anything else.

**Comment by justinmoor** [comment]
Clear story. Thanks for commenting all!

**Comment by mabartibin** [comment]
Let me dig this up from the vault…

My understanding is that the typical video input of a monitor will have a 75 Ohm impedance, matching the impedance of video coax cable.  That may well be too much loading for the TMS9918 COMVID output.

As far as I can tell, this was already the norm in 1982, so I don’t know what TI had in mind saying that no buffer is needed in all but "some cases".  No buffer would be needed if the signal goes straight to an RF modulator.

I found the schematics of the Yamaha CX5M, and here, in a corner of the schematics, is your video signal buffer.  "Video In" comes from the TMS9918.

<img width="579" height="540" alt="Image" src="https://github.com/user-attachments/assets/f97124f0-151b-45af-b0a8-fe58fcfd8ee8" />
